### ISSUE TITLE
UserLogBasic and UserLogAdvanced don't use the logbook created in UserLogCreate

### ISSUE THREAD

**Issue by ben-jammin-beckvold** [tmatijevich/UserLog#4]
creating a new log book in INIT works and I can see it as a new log book in the logger. However any further calls in CYCLIC to either `UserLogBasic` or `UserLogAdvanced` puts any of the new log messages in $USER. It does display them as expected and reports the "Entered By" correctly of the program of origin. the custom log book remains empty except for the "Log module <> created" message.

I can get around it with `UserLogCustom` and I specify the log name each time.

I think within `custom.c` you are hard coding `LOGBOOK_USER_NAME` to each call to `UserLogCustom`. Line 109 and Line 117.

My suggestion for a quick fix is to have the user pass in the log book name to `UserLogBasic` as the first parameter and just pass that through to UserLogCustom.

Another suggestion could be to store the log name in the library somewhere but i'm not sure how to implement that.

Let me know if I can help.

**Comment by tmatijevich** [comment]
Hi, your point is well taken and I commend you for reading into the code!

Let me share some design decisions based on system properties.
- The [User](https://help.br-automation.com/#/en/4/diagnostics_support%2Fdiagnosis%2Flogger%2Fdiagnosis_logger_brlogbooks.html) (`$arlogusr`) logbook is automatically created by the system and is intended for this exact purpose - a location to write messages from the user.
- The [User](https://help.br-automation.com/#/en/4/diagnostics_support%2Fdiagnosis%2Flogger%2Fdiagnosis_logger_brlogbooks.html) (`$arlogusr`) is the only system-created logbook users can write to.  Users cannot [write](https://help.br-automation.com/#/en/4/libraries%2Fareventlog%2Ffbks%2Fareventlogwrite.html) to any other system logbook (and the system will not write to the User logbook).
- [UserLogCreate](https://github.com/tmatijevich/UserLog/blob/main/UserLog.fun#L43) is an optional function to create one _or more_ **custom** user logbooks.
    - Since it's possible to create as many logbook as can fit on the storage medium, there's no productive way to store the logbook name in the function's static memory.
    - [UserLogCustom](https://github.com/tmatijevich/UserLog/blob/main/UserLog.fun?ts=4#L19) is intended to use with custom created logbooks.
- [UserLogBasic](https://github.com/tmatijevich/UserLog/blob/main/UserLog.fun?ts=4#L2) and [UserLogAdvanced](https://github.com/tmatijevich/UserLog/blob/main/UserLog.fun?ts=4#L10) are designed to write to _the_ **User** logbook.
    - These functions were designed to have as few of input parameters as possible.

To achieve the parameters you want in your case, I would copy the code and adjust the parameters you like.  Or write a wrapper around UserLogCustom.

**Comment by ben-jammin-beckvold** [comment]
Awesome, thank you so much for your quick response. I understand the intent now and will make adjustments. I appreciate project.
